spring:
  datasource:

    #Postgres IP address/port number/DB name
    url: jdbc:postgresql://localhost:5432/postgres

    #Postgres username
    username: postgres

    #Postgres password
    password: mysecretpassword

    #Postgres JDBC driver
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:

      # @Always drop the table corresponding to Entity&create.
      ddl-auto: none

      # define schema
      properties:
        hibernate:
          default_schema: public

    thymeleaf:
      prefix: classpath:/templates/
